import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import Header from "@components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],      
  weight: ['400', '500', '700'], 
  display: 'swap'            
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
          <Header/>
          {children}
      </body>
    </html>
  );
}
